services:
  fastfony_license.response_subscriber:
    class: Fastfony\LicenseBundle\EventSubscriber\ResponseSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
      $licenseChecker: "@fastfony_license.security.license_checker"
    tags:
        - { name: kernel.event_subscriber }

  fastfony_license.security.license_checker:
    class: Fastfony\LicenseBundle\Security\LicenseChecker

  fastfony_license.validator.valid_license_key:
    class: Fastfony\LicenseBundle\Validator\ValidLicenseKeyValidator
    arguments:
      $licenseChecker: "@fastfony_license.security.license_checker"
    tags:
      - { name: validator.constraint_validator }

  fastfony_license.constraint.valid_license_key:
    class: Fastfony\LicenseBundle\Validator\ValidLicenseKey
    tags:
      - { name: validator.constraint }
