services:
  fastfony_licence.response_subscriber:
    class: Fastfony\LicenceBundle\EventSubscriber\ResponseSubscriber
    arguments:
      $parameterBag: "@parameter_bag"
      $licenceChecker: "@fastfony_licence.security.licence_checker"
    tags:
        - { name: kernel.event_subscriber }

  fastfony_licence.security.licence_checker:
    class: Fastfony\LicenceBundle\Security\LicenceChecker

  fastfony_licence.validator.valid_licence_key:
    class: Fastfony\LicenceBundle\Validator\ValidLicenceKeyValidator
    arguments:
      $licenceChecker: "@fastfony_licence.security.licence_checker"
    tags:
      - { name: validator.constraint_validator }

  fastfony_licence.constraint.valid_licence_key:
    class: Fastfony\LicenceBundle\Validator\ValidLicenceKey
    tags:
      - { name: validator.constraint }
